---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:

    - name: Get Timestamp from system
      shell: "date +%Y-%m-%d"
      register: tstamp

    - name: set facts
      set_fact:
       cur_date: "{{ tstamp.stdout[0:10]}}"

    - name: parse csv and make vars file
      command: "python3 scripts/dhcpscopes_csv_to_yaml.py {{source_csv_prefix}}.csv"

    - name: Include source yaml file
      include_vars: "{{source_csv_prefix}}.csv.yml"


    - name: Build DHCP Config file
      template:
          src=templates/rphydhcpscopes.j2
      register: dhcpoutput
    
    - name: Build CIN Leaf Config file
      template:
          src=templates/rphycin-leaf.j2
      register: cinoutput
