---
- hosts: localhost
  connection: local
  become: false
  gather_facts: false
  tasks:

    - name: Get Timestamp from system
      shell: "date +%Y-%m-%d"
      register: tstamp

    - name: set facts
      set_fact:
       cur_date: "{{ tstamp.stdout[0:10]}}"

    - name: parse csv and make vars file
      command: "python3 scripts/rphydpic_csv_to_yaml.py {{source_csv_prefix}}.csv"

    - name: Include source yaml file
      include_vars: "{{source_csv_prefix}}.csv.yml"


    - name: Build CBR8 Configs
      template:
          src=templates/rphycbr8.j2
          dest=configs/cbr8-{{source_csv_prefix}}.txt
          
    - name: Build CIN Leaf to DPIC Switch Configs      
      template:
          src=templates/rphycindpic-leaf.j2
          dest=configs/cindpic-{{source_csv_prefix}}.txt
          
    - name: Build PHP IPAM Subnet Import file
      template:
          src=templates/phpipam_subnet.j2
          dest=configs/{{source_csv_prefix}}-subnet.csv 

    - name: Build PHP IPAM IP Address Import file
      template:
          src=templates/phpipam_ipaddress.j2
          dest=configs/{{source_csv_prefix}}-ipaddress.csv

    - mail:
        host: "{{smtphost}}"
        port: 25
        from: "{{email}}"
        to: "{{email}}"
        subject: "{{source_csv_prefix}} RPHY Configs"
        body: 'RPHY Config Results attached'
        attach:
        - configs/cbr8-{{source_csv_prefix}}.txt
        - configs/cindpic-{{source_csv_prefix}}.txt
        - configs/{{source_csv_prefix}}-subnet.csv
        - configs/{{source_csv_prefix}}-ipaddress.csv
